# https://medium.com/statuscode/dockerising-a-node-js-and-mongodb-app-d22047e2806f
version: "1"
services:
  web:
    container_name: personadb
    # pull the image from registry
    image: khaiphong/personadb:latest
    volumes:
      - /khaiphong/personadb
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # share port 8080 via a load-balanced network called webnet
    ports:
      - "8080:8080"
    networks:
      - webnet
# use default webnet settings (which is a load-balanced overlay network)
networks:
  webnet:
